# .github/codecov.yml

comment:
  layout: "reach,diff,files,flags"  # Control report sections
  behavior: default                 # 'once' to prevent multiple comments
  require_changes: false            # Show report even if no coverage changes
  show_carryforward_flags: true     # Show coverage carried forward from base branch

coverage:
  status:
    project:                        # Overall project status
      default:                      # Applies to all flags
        target: 80%                 # Fail if coverage < 80%
        threshold: 5%               # Allow 5% decrease before failing
    patch:                         # Changed files only
      default:
        target: 70%                 # Lower threshold for new changes
        threshold: 0%               # Fail on any decrease

flags:
  frontend:
    paths: 
      - "Frontend/"
    carryforward: true              # Track coverage history separately
    status:
      target: 85%                   # Higher standard for frontend

  backend:
    paths:
      - "Backend/"
    carryforward: true
    status:
      target: 75%                   # Lower threshold for backend

parsers:
  gcov:
    branch_demotion: 10             # Reduce branch coverage weight

ignore:
  - "**/test/**"                   # Exclude test files from coverage
  - "**/*.d.ts"                    # Exclude TypeScript declarations
  - "**/Generated/**"              # Exclude auto-generated code

codecov:
  require_ci_to_pass: true          # Block PRs if coverage check fails

annotations:
  - path: "src/"                   # Where to show line annotations
    annotation_type: diff           # Show only changed lines
    range: 0-100                   # Coverage percentage range to annotate

comment_templates:
  header: "## Coverage Report"
  footer: "_[Generated by Codecov]()_"