name: Build and Test

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore CertAtheon.sln

      - name: Build
        run: dotnet build CertAtheon.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test CertAtheon.sln --configuration Release --no-build --verbosity normal

      - name: Publish Backend
        run: dotnet publish Backend/Backend.csproj -c Release -o ${{ github.workspace }}/publish

      - name: Zip artifacts
        run: Compress-Archive -Path ${{ github.workspace }}/publish/* -DestinationPath ${{ github.workspace }}/app.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-artifact
          path: ${{ github.workspace }}/app.zip