name: Upload Coverage Report to Barecheck

on:
  pull_request:
    branches: [ "main", "development" ]
  push:
    branches: [ "main", "development" ]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore and Build
      run: |
        dotnet restore
        dotnet build --no-restore

    - name: Run tests and generate coverage report
      run: |
        dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults --no-build

    - name: Upload Coverage to Barecheck
      uses: barecheck/github-action@v1
      with:
        token: ${{ secrets.BARECHECK_TOKEN }}
        coverage-file: ./TestResults/**/coverage.cobertura.xml