name: Deploy to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:  # Required independent job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build
        run: dotnet build --configuration Release

  deploy:
    runs-on: windows-latest
    needs: build  # Now valid since we have an independent job
    environment: Production
    steps:
      # Your existing deploy steps here
      - uses: actions/download-artifact@v4
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'CSCE590'
          package: ./app.zip