name: Build & Deploy ASP.NET Core to Azure

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/

      - name: Build solution
        run: dotnet build Backend/ --configuration Release --no-restore

      - name: Publish .NET app
        run: dotnet publish Backend/ -c Release -o publish
      
      - name: Build Frontend
        run: |
          cd Frontend
          npm install
          npm run build

      - name: Run tests (optional)
        run: dotnet test Backend/ --no-build --verbosity normal
        continue-on-error: true # Optional: don't block deployment if tests fail

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: CSCE590 
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish/
