name: Build & Deploy ASP.NET Core to Azure

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add Node.js setup step (critical for frontend)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or your preferred LTS version
          cache: 'npm'
          cache-dependency-path: 'Frontend/package-lock.json'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/

      - name: Build App
        run: dotnet build Backend/ --configuration Release --no-restore

      - name: Build Frontend
        run: |
          cd Frontend
          npm ci
          npm install -D tailwindcss postcss autoprefixer # Explicitly install missing deps
          npm run build
      
      - name: Copy Frontend into Backend/ClientApp
        run: |
          mkdir -p Backend/ClientApp
          cp -r Frontend/dist/* Backend/ClientApp/

      - name: Publish .NET app
        run: dotnet publish Backend/ -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: CSCE590
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish/