name: Build & Test .NET Project

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Backend/

      - name: Build solution
        run: dotnet build Backend/ --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Backend/ --no-restore --verbosity normal
