name: Super-Linter CI

on:
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false  # Set to true to lint all files, false to lint only changed files
          VALIDATE_CSHARP: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_PYTHON: true
          VALIDATE_YAML: true
          VALIDATE_HTML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_CSS: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_SHELL_SHFMT: true
