name: Frontend Tests (Vite)

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: Frontend
        run: npm run test

      - name: Upload Frontend Test Report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: frontend-test-results
          path: Frontend/reports/vitest-junit.xml

      - name: Publish Frontend Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Frontend Tests (Vitest)
          path: Frontend/reports/vitest-junit.xml
          reporter: jest-junit
